#ifndef EXITCODES_H
#define EXITCODES_H

#define ERROR_CRITICAL 1000
#define ERROR_LOG_IN_USE 1001
#define ERROR_COULD_NOT_OPEN_LOG 1002
#define ERROR_COULD_NOT_OPEN_APPDATA 1003
#define ERROR_COULD_NOT_CREATE_LOG_FOLDER 1004
#define ERROR_COULD_NOT_READ_LOG_FOLDER 1005
#define ERROR_COULD_NOT_CREATE_APPDATA 1006

#endif // EXITCODES_H
